name = "ProjetBlackJack"
uuid = "f1ad940b-4e07-4a9a-8f83-e1ed8661e808"
authors = ["Garance MalnoÃ« <106530489+malnoe@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Vizagrams = "8c229dad-8b3a-4031-83d6-73545c88426d"

[compat]
Downloads = "1.6.0"
HypertextLiteral = "0.9.5"
Pluto = "0.20.3"
PlutoUI = "0.7.60"
PyCall = "1.96.4"
Random = "1.11.0"
Vizagrams = "0.2.10"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
